window.__justep.__ResourceEngine.loadCss([{url: '/UI2/system/components/bootstrap.min.css', include: '$model/UI2/system/components/bootstrap/lib/css/bootstrap,$model/UI2/system/components/bootstrap/lib/css/bootstrap-theme'},{url: '/UI2/system/components/comp.min.css', include: '$model/UI2/system/components/justep/lib/css2/dataControl,$model/UI2/system/components/justep/input/css/datePickerPC,$model/UI2/system/components/justep/messageDialog/css/messageDialog,$model/UI2/system/components/justep/lib/css3/round,$model/UI2/system/components/justep/input/css/datePicker,$model/UI2/system/components/justep/row/css/row,$model/UI2/system/components/justep/dataTables/css/responsive,$model/UI2/system/components/justep/attachment/css/attachment,$model/UI2/system/components/justep/barcode/css/barcodeImage,$model/UI2/system/components/bootstrap/dropdown/css/dropdown,$model/UI2/system/components/justep/contents/css/contents,$model/UI2/system/components/justep/common/css/forms,$model/UI2/system/components/justep/dataTables/css/responsive,$model/UI2/system/components/justep/locker/css/locker,$model/UI2/system/components/justep/menu/css/menu,$model/UI2/system/components/justep/scrollView/css/scrollView,$model/UI2/system/components/justep/loadingBar/loadingBar,$model/UI2/system/components/justep/dialog/css/dialog,$model/UI2/system/components/justep/bar/css/bar,$model/UI2/system/components/justep/popMenu/css/popMenu,$model/UI2/system/components/justep/lib/css/icons,$model/UI2/system/components/justep/lib/css4/e-commerce,$model/UI2/system/components/justep/toolBar/css/toolBar,$model/UI2/system/components/justep/popOver/css/popOver,$model/UI2/system/components/justep/panel/css/panel,$model/UI2/system/components/bootstrap/carousel/css/carousel,$model/UI2/system/components/justep/wing/css/wing,$model/UI2/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/UI2/system/components/justep/titleBar/css/titleBar,$model/UI2/system/components/justep/lib/css1/linear,$model/UI2/system/components/justep/numberSelect/css/numberList,$model/UI2/system/components/justep/list/css/list,$model/UI2/system/components/justep/dataTables/css/dataTables'}]);window.__justep.__ResourceEngine.loadJs(['/system/core.min.js','/system/common.min.js','/system/components/comp.min.js']);define(function(require){
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/input/input');
require('$model/UI2/system/components/justep/scrollView/scrollView');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/textarea/textarea');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/popOver/popOver');
require('$model/UI2/system/components/justep/contents/content');
require('$model/UI2/system/components/justep/row/row');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/contents/contents');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/button/buttonGroup');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/buctwebvpn/activities'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='';
	this.__cid='cMvEnIf';
	this._flag_='16a9801f17afcb39fc2b9303e912e259';
	this._wCfg_={};
	this._appCfg_={};
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"fActivityEnd":{"define":"fActivityEnd","label":"活动结束时间","name":"fActivityEnd","relation":"fActivityEnd","type":"String"},"fActivityPlace":{"define":"fActivityPlace","label":"活动地点","name":"fActivityPlace","relation":"fActivityPlace","type":"String"},"fActivityStart":{"define":"fActivityStart","label":"活动开始时间","name":"fActivityStart","relation":"fActivityStart","type":"String"},"fCount":{"define":"fCount","label":"容量","name":"fCount","relation":"fCount","rules":{"integer":true},"type":"Integer"},"fName":{"define":"fName","label":"活动名称","name":"fName","relation":"fName","type":"String"},"fNowCount":{"define":"fNowCount","label":"已报名人数","name":"fNowCount","relation":"fNowCount","rules":{"integer":true},"type":"Integer"},"fPushDW":{"define":"fPushDW","label":"发布单位","name":"fPushDW","relation":"fPushDW","type":"String"},"fSelfDW":{"define":"fSelfDW","label":"主办方","name":"fSelfDW","relation":"fSelfDW","type":"String"},"fSignEnd":{"define":"fSignEnd","label":"报名结束时间","name":"fSignEnd","relation":"fSignEnd","type":"String"},"fSignStart":{"define":"fSignStart","label":"报名开始时间","name":"fSignStart","relation":"fSignStart","type":"String"},"id":{"define":"id","label":"id","name":"id","relation":"id","type":"String"},"typeName":{"define":"typeName","label":"活动类型","name":"typeName","relation":"typeName","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"activitiesDataCustomRefresh"},"idColumn":"id","isMain":false,"limit":20,"xid":"activitiesData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"fActivityEnd":{"define":"fActivityEnd","label":"活动结束时间","name":"fActivityEnd","relation":"fActivityEnd","type":"String"},"fActivityPlace":{"define":"fActivityPlace","label":"活动地点","name":"fActivityPlace","relation":"fActivityPlace","type":"String"},"fActivityStart":{"define":"fActivityStart","label":"活动开始时间","name":"fActivityStart","relation":"fActivityStart","type":"String"},"fCount":{"define":"fCount","label":"容量","name":"fCount","relation":"fCount","rules":{"integer":true},"type":"Integer"},"fName":{"define":"fName","label":"活动名称","name":"fName","relation":"fName","type":"String"},"fPushDW":{"define":"fPushDW","label":"发布单位","name":"fPushDW","relation":"fPushDW","type":"String"},"fSelfDW":{"define":"fSelfDW","label":"主办方","name":"fSelfDW","relation":"fSelfDW","type":"String"},"fSignEnd":{"define":"fSignEnd","label":"报名结束时间","name":"fSignEnd","relation":"fSignEnd","type":"String"},"fSignStart":{"define":"fSignStart","label":"报名开始时间","name":"fSignStart","relation":"fSignStart","type":"String"},"id":{"define":"id","label":"id","name":"id","relation":"id","type":"String"},"status":{"define":"status","label":"审核状态","name":"status","relation":"status","type":"String"},"typeName":{"define":"typeName","label":"活动类型","name":"typeName","relation":"typeName","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"data1CustomRefresh"},"idColumn":"id","isMain":false,"limit":20,"xid":"data1"});
}}); 
return __result;});
